# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField()),
                ('score1', models.IntegerField(null=True)),
                ('score2', models.IntegerField(null=True)),
                ('score1_adjusted', models.IntegerField(null=True)),
                ('scor2_adjusted', models.IntegerField(null=True)),
                ('result', models.FloatField(default=0)),
                ('position', models.IntegerField(default=0, null=True)),
                ('first', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='pairing.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='pairing.Player')),
            ],
        ),
    ]
