# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pairing.Round')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pairing.Player')),
            ],
        ),
        migrations.RenameField(
            model_name='result',
            old_name='scor2_adjusted',
            new_name='score2_adjusted',
        ),
        migrations.RemoveField(
            model_name='result',
            name='first',
        ),
        migrations.RemoveField(
            model_name='result',
            name='position',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result',
        ),
        migrations.AlterField(
            model_name='result',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pairing.Round'),
        ),
    ]
