# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0003_auto_20170513_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='pairing.Player'),
        ),
        migrations.AlterField(
            model_name='result',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='pairing.Player'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pairing.Player'),
        ),
    ]
